### ISSUE TITLE
跟另一个项目很多代码相同

### ISSUE THREAD

**Issue by mcxinyu** [yangchaojiang/ChatKeyboard-master#1]
发现这个项目跟两一个项目代码相同，甚至注释都相同，就改了头注释。

两位作者（其实作者只有一位）谁是源头呢？

世界很小，原则还是要有的。

https://github.com/CPPAlien/ChatKeyboard/issues/21#issue-749295127

**Comment by yangchaojiang** [comment]
这是自己用的，定制化的，不是用来分享的
